<?php

    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0)
    {
	    $this->product_image_disp = false;
    }
    $uniqued = rand().time();
?>

<?php
    function random($max)
    {
        $random = rand(1, $max);
        $bgClass = "randomClass".$random;
        return $bgClass;
    }
?>

<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="wm_productslider<?php echo $uniqued; ?>" class="wm-productslider wm_slideshow_block"><div class="slider-inner">
    <div class="main">
    <div class="title-slider"><?php echo $this->title;?></div>
    <?php if($this->pretext): ?>
    <div class="pretext"><div><?php echo $this->pretext; ?></div></div>
    <?php endif; ?>

    <ul class="container-slider products-grid clearfix">
    <?php foreach($_productCollection as $_product){?>
        <?php
        $now = date("Y-m-d");
        $newsFrom= substr($_product->getData('news_from_date'),0,10);
        $newsTo=  substr($_product->getData('news_to_date'),0,10);
        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
        $class = '';
        if($now>=$newsFrom && $now<=$newsTo) $class .= ' have-iconew';
        if($specialprice) $class .= ' have-icosale';
        ?>
        <li class="item <?php echo random(5); ?>">
            <div class="item-inner">
                <?php if( $this->product_title_disp == 1 ){?>
                    <div class="item-title">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <?php
                        if ( $this->product_title_max_length > 0){
                            $_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
                        }
                        ?>
                        <h3>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                        </h3>
                    </div>
                <?php }?>
                <div class="item-img<?php echo $class; ?><?php echo (count(Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages()) > 0)?' have-additional':'';?>">
                    <div class="item-img-info">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <span class="img-main">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            </span>
                        </a>
                    </div>
                    <div class="item-box-hover">
                        <div class="box-inner">
                            <?php if ($this->product_cart_or_status): ?>
                            <?php if($_product->isSaleable()): ?>
                            <div class="cart">
                                <button title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Cart') ?>"><?php echo $this->__('Add to Cart') ?></button>
                            </div>
                            <?php else: ?>
                                <span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                            <?php endif; ?>
                            <?php endif; ?>
                            <?php if($this->product_addtowishlist || $this->product_addtocompare): ?>
                            <div class="actions">
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow() && $this->product_addtowishlist ) : ?>
                                        <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($this->getAddToCompareUrl($_product) && $this->product_addtocompare): ?>
                                        <li><a title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $this->getAddToCompareUrl($_product) ?>" class="link-compare" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                            <div class="quickview-wrap">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" style="display:none"></a>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="item-info">
                    <div class="info-inner">

                        <div class="item-content">
                            <?php if( $this->product_description_disp == 1 ){?>
                            <div class="item-des">
                                <?php
                                $product_description_src = in_array($this->product_description_src, array('short_description', 'description')) ? $this->product_description_src : 'short_description';
                                $product_description = $_helper->productAttribute($_product, $_product->$product_description_src, $product_description_src);
                                if ( $this->product_description_strip_tags ){
                                    $allow_tags = $this->product_description_keep_tags ? $this->product_description_keep_tags : null;
                                    $product_description = $this->stripTags( $product_description,  $allow_tags, true);
                                }
                                if ( $this->product_description_max_length > 0){
                                    $product_description = Mage::helper('core/string')->truncate($product_description, (int)$this->product_description_max_length);
                                }
                                echo $product_description;
                                ?>
                            </div>
                            <?php }
                            if( $this->product_price_disp ){ ?>
                            <div class="item-price">
                                <?php echo $this->getPriceHtml($_product, false, $uniqued) ?>
                            </div>
                            <?php }?>
                            <?php
                            if( $this->product_rating_summary == 1 ){ ?>
                            <div class="rating">
                            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                            </div>
                            <?php } ?>
                            <?php
                            if ($now>=$newsFrom && $now<=$newsTo)
                                echo "<span class='ico-product ico-new'>new</span>";
                            if ($specialprice)
                                echo "<span class='ico-product ico-sale'>sale</span>";
                            ?>
                        </div>
                    </div>
                </div>
                <div class="mask-hover"></div>
            </div>
        </li>
    <?php }?>
    </ul>

    <div class="timer"></div>
    <?php if($this->posttext): ?>
    <div class="posttext"><div><?php echo $this->posttext; ?></div></div>
    <?php endif; ?>
</div>
</div>
    <?php if($this->navigation){ ?>
        <div class="navigation">
            <span class="next"><span></span></span>
            <span class="prev"><span></span></span>
        </div>
    <?php } ?>
</div>


<script type="text/javascript">
//<![CDATA[
    $wm_jq(window).load(function(){
        var carousel = $wm_jq('#wm_productslider<?php echo $uniqued; ?> ul.container-slider');
        carousel.carouFredSel({
            responsive: true,
            width: '100%',
            /*padding:[0, 0, 0, 30],*/
            scroll: {
                items:<?php echo $this->items_scroll ?>,
                duration:<?php echo $this->duration ?>
            },

            items: {
                width: <?php echo $this->product_image_width + 45 ?>,
                height: 'auto',  //  optionally resize item-height
                visible: {
                    min: 1,
                    max: <?php echo $this->product_limitation ?>
                }
            },
            <?php if($this->navigation):?>
            prev: '#wm_productslider<?php echo $uniqued; ?> .navigation .prev',
            next: '#wm_productslider<?php echo $uniqued; ?> .navigation .next',
            <?php endif; ?>
            /*mousewheel: true,
            swipe: {
                onMouse: true,
                onTouch: true
            },*/
            onCreate : function () {
                $wm_jq(window).on('resize', function(){
                    carousel.parent().add(carousel).css('height', carousel.children().first().outerHeight() + 'px');
                }).trigger('resize');
            }
            <?php if($this->loader): ?>
            ,
            auto: {
                    pauseOnHover: 'resume',
                    progress: '#wm_productslider<?php echo $uniqued; ?> .timer'
                }
                }, {
                    transition: true
            <?php else: ?>
            ,
            auto: <?php echo($this->auto == 1)?'true':'false'; ?>
            <?php endif; ?>
        });
        $wm_jq('#wm_productslider<?php echo $uniqued; ?>').find('.caroufredsel_wrapper').append('<span class="fix-hor"></span>');
    });
//]]>
</script>
<?php endif; ?>